# Generated by Django 5.0 on 2023-12-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Socio_app', '0003_users_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.RemoveField(
            model_name='story',
            name='title',
        ),
    ]
