# Generated by Django 5.0 on 2023-12-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socio_app', '0006_rename_user_activefriend_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upost',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
    ]
