# Generated by Django 5.0 on 2023-12-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socio_app', '0007_upost_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='upost',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
