# Generated by Django 5.0 on 2023-12-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socio_app', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='postinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='posts/')),
                ('video', models.FileField(upload_to='posts/')),
                ('description', models.TextField()),
            ],
        ),
    ]
